productsSample = [
    "Mã lỗi E206 có ý nghĩa gì?",
    "Mã lỗi E305 có ý nghĩa gì?",
    "Mã lỗi E902 là lỗi gì?",
    "Nguyên nhân gây ra lỗi E803 là gì?",
    "Giải thích về mã lỗi E224.",
    "What does error code E10006 mean?",
    "Why does error code E310 occur?",
    "What is the meaning of error code E891?",
    "What is the cause of error code E304?",
    "Why does error code E107 happen?",
    "Tại sao xảy ra lỗi 'Abort at location PC136'?",
    "Vì sao lỗi 'Board Online (CMWRRAP/DBG)' xuất hiện?",
    "What causes the error 'Board Online (CMWRRAP/DBG)' at location D142?",
    "What is the reason for the error 'Board not online (No test log)' at location DIM0?",
    "Nguyên nhân lỗi 'Failed to kill JIT process' at PSU PN_1 là gì?",
    "Why does the error 'LED OFF' at location DDLED29 occur?",
    "Tại sao lỗi 'Port Bad' at location lại xảy ra?",
    "What is the cause of 'POE test fail' at location DIM 0?",
    "What causes the 'USBTEST' at location J10 error?",
    "Nguyên nhân lỗi 'Wrong Firmware version' at location U10 là gì?",
    "Giải pháp cho lỗi 'Board Online (CMWRRAP/DBG)' là gì?",
    "Cách khắc phục lỗi 'Solder Bridge' tại vị trí CN5?",
    "What is the solution for error code E803?",
    "Cách xử lý lỗi 'Memory test fail at PC634'?",
    "What should be done if the error 'Assembly Gap at CABLE IN OOB BOARD' occurs?",
    "Giải pháp khi gặp lỗi 'PORT LINK DOWN at location D165'?",
    "How to fix the issue 'Programmable part content error at U6'?",
    "Cách sửa lỗi 'Defect Component' tại vị trí Q18?",
    "What should be done when 'Damaged Component' is detected at D137?",
    "How to resolve the issue 'Reprogram needed at location U5'?",
    "Những vị trí nào thường gặp lỗi 'Board Online (CMWRRAP/DBG)'?",
    "Where does the 'Solder Bridge' issue commonly occur?",
    "Vị trí nào dễ gặp lỗi 'Defect Component'?",
    "What are the common locations for 'Assembly Gap' errors?",
    "Những vị trí nào hay bị lỗi 'NTF'?",
    "Which components frequently experience the error 'Wrong serial number'?",
    "Các vị trí nào dễ gặp lỗi 'Colder Solder'?",
    "Where do 'Memory test fail' errors usually appear?",
    "Những vị trí phổ biến gặp lỗi 'Open Solder' là gì?",
    "Which locations often show 'Firmware Wrong' errors?",
    "What are the most common errors between 2024-08-28 and 2024-10-28?",
    "Trong tháng 9, lỗi nào xảy ra thường xuyên nhất?",
    "What is the most frequent cause of errors in October?",
    "Các lỗi phổ biến nhất trong quý 3 năm 2024 là gì?",
    "Which stations had the highest number of 'Board Online (CMWRRAP/DBG)' errors in the last two months?",
    "Bao nhiêu lần lỗi 'Abort at location PC136' xảy ra trong tháng 8?",
    "Which months recorded the most 'Defect Component' issues?",
    "How often does the error 'Assembly Gap' occur in a given period?",
    "Tần suất xảy ra lỗi 'LED OFF at location DDLED29' là bao nhiêu?",
    "Giải pháp cho lỗi 'Board Online (CMWRRAP/DBG)' ở trạm BFT là gì'",
    "In which period did 'Wrong Firmware version' errors peak?",
    "错误代码 E206 的含义是什么?",
    "错误代码 E305 的含义是什么?",
    "错误代码 E902 是什么错误?",
    "导致错误 E803 的原因是什么?",
    "解释错误代码 E224。",
    "错误代码 E10006 的含义是什么?",
    "为什么会发生错误代码 E310?",
    "错误代码 E891 的含义是什么?",
    "错误代码 E304 的原因是什么?",
    "为什么会发生错误代码 E107?",
    "为什么会出现错误 'Abort at location PC136'?",
    "为什么会出现错误 'Board Online (CMWRRAP/DBG)'?",
    "是什么导致在位置 D142 出现错误 'Board Online (CMWRRAP/DBG)'?",
    "在位置 DIM0 出现错误 'Board not online (No test log)' 的原因是什么?",
    "在 PSU PN_1 位置出现错误 'Failed to kill JIT process' 的原因是什么?",
    "为什么在位置 DDLED29 会发生错误 'LED OFF'?",
    "为什么会发生错误 'Port Bad'?",
    "在位置 DIM0 发生 'POE test fail' 错误的原因是什么?",
    "是什么导致位置 J10 发生 'USBTEST' 错误?",
    "在位置 U10 出现错误 'Wrong Firmware version' 的原因是什么?",
    "错误 'Board Online (CMWRRAP/DBG)' 的解决方案是什么?",
    "如何修复位置 CN5 的 'Solder Bridge' 错误?",
    "错误代码 E803 的解决方案是什么?",
    "如何处理 'Memory test fail at PC634' 错误?",
    "如果发生错误 'Assembly Gap at CABLE IN OOB BOARD'，应该怎么办?",
    "当遇到错误 'PORT LINK DOWN at location D165' 时，该如何解决?",
    "如何修复 'Programmable part content error at U6'?",
    "如何修复位置 Q18 的 'Defect Component' 错误?",
    "当在 D137 位置检测到 'Damaged Component' 时应该怎么办?",
    "如何解决 'Reprogram needed at location U5' 的问题?",
    "哪些位置最常发生 'Board Online (CMWRRAP/DBG)' 错误?",
    "'Solder Bridge' 问题通常发生在哪些位置?",
    "哪些位置容易出现 'Defect Component' 错误?",
    "'Assembly Gap' 错误通常出现在什么位置?",
    "哪些位置容易出现 'NTF' 错误?",
    "哪些组件经常发生 'Wrong serial number' 错误?",
    "哪些位置容易出现 'Colder Solder' 错误?",
    "'Memory test fail' 错误通常出现在什么位置?",
    "'Open Solder' 错误最常出现在哪些位置?",
    "哪些位置经常显示 'Firmware Wrong' 错误?",
    "在 2024-08-28 到 2024-10-28 之间最常见的错误是什么?",
    "在九月份，最常发生的错误是什么?",
    "十月份错误最常见的原因是什么?",
    "2024 年第三季度最常见的错误是什么?",
    "在过去两个月中，哪些站点发生 'Board Online (CMWRRAP/DBG)' 错误最多?",
    "在八月份，'Abort at location PC136' 发生了多少次?",
    "哪些月份记录了最多的 'Defect Component' 错误?",
    "在某一特定时间段内，'Assembly Gap' 错误发生的频率是多少?",
    "'LED OFF at location DDLED29' 发生的频率是多少?",
    "'Board Online (CMWRRAP/DBG)' 在 BFT 站点的解决方案是什么?",
    "'Wrong Firmware version' 错误在什么时间段达到峰值?"
]


chitchatSample = [
    "Hello, how are you",
    "你好吗",
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
    "What is the weather like today?",
    "How hot is it outside?",
    "Will it rain tomorrow?",
    "What is the current temperature?",
    "Can you tell me the current weather conditions?",
    "Will it be sunny this weekend?",
    "What was the temperature yesterday?",
    "How cold will it be tonight?",
    "Who was the first president of the United States?",
    "When did World War II end?",
    "Can you tell me about the history of the internet?",
    "When was the Eiffel Tower built?",
    "Who invented the telephone?",
    "What is your name?",
    "Do you have a name?",
    "What should I call you?",
    "Who created you?",
    "How old are you?",
    "Can you tell me an interesting fact?",
    "Do you know any fun riddles?",
    "What is your favorite color?",
    "What is your favorite movie?",
    "Do you have any hobbies?",
    "What is the meaning of life?",
    "Can you tell me a joke?",
    "What is the capital of France?",
    "What is the world's population?",
    "How many continents are there?",
    "Who wrote 'To Kill a Mockingbird'?",
    "Can you give me a quote from Albert Einstein?",
    "今天天气怎么样?",
    "外面有多热?",
    "明天会下雨吗?",
    "当前温度是多少?",
    "你能告诉我当前的天气状况吗?",
    "这个周末会是晴天吗?",
    "昨天的温度是多少?",
    "今晚会有多冷?",
    "谁是美国第一任总统?",
    "第二次世界大战是什么时候结束的?",
    "你能告诉我互联网的历史吗?",
    "埃菲尔铁塔是什么时候建造的?",
    "谁发明了电话?",
    "你叫什么名字?",
    "你有名字吗?",
    "我应该怎么称呼你?",
    "是谁创造了你?",
    "你多大了?",
    "你能告诉我一个有趣的事实吗?",
    "你知道什么有趣的谜语吗?",
    "你最喜欢的颜色是什么?",
    "你最喜欢的电影是什么?",
    "你有什么爱好吗?",
    "生命的意义是什么?",
    "你能讲个笑话吗?",
    "法国的首都是哪里?",
    "世界人口有多少?",
    "世界上有多少个大洲?",
    "谁写了《杀死一只知更鸟》?",
    "你能给我一句爱因斯坦的名言吗?",
]
